FROM python:3.12-slim
LABEL authors="tz2m"

WORKDIR /app

# Instala o LibreOffice mínimo necessário
RUN apt-get update && apt-get install -y --no-install-recommends \
    libreoffice-core \
    libreoffice-writer \
    libreoffice-calc \
    libreoffice-impress \
    default-jre \
    libreoffice-java-common \
    && rm -rf /var/lib/apt/lists/*


COPY src /app
COPY ctr_util/src /app
COPY requirements-sync.txt .
RUN pip install --no-cache-dir --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org -r requirements-sync.txt
EXPOSE 5433

ENTRYPOINT ["python", "-m", "domains.sinpet.sync_job"]
CMD []