FROM python:3.12-slim
LABEL authors="tz2m"

WORKDIR /app

# Instala o LibreOffice mínimo necessário
COPY src /app
COPY ctr_util/src /app
COPY requirements-backend.txt .

RUN pip install --no-cache-dir --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org -r requirements-backend.txt
EXPOSE 8000

# Define o comando de entrada
ENTRYPOINT ["uvicorn", "domains.sinpet.web:app", "--host", "0.0.0.0", "--port", "8000"]
CMD []